site_name: CarRent Documentation
site_url: https://ragi96.github.io/CarRent/
repo_url: https://github.com/ragi96/CarRent
repo_name: ragi96/CarRent
theme:
  name: material
  features: 
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
plugins:
  - render_swagger
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true